// Route data-model
// Holds a description of a route, as generated by any of the services in the "routing" namespace
// ----------------------------------------------------------------------------

/**
 * Route definition
 */
export class Route {
  /**
   * Instantiates a new Route
   * @param path Route path
   * @param title Route title
   * @param component Route component
   * @param parentRoute (Optional) Parent route
   * @param childRoutes (Optional) Child routes
   */
  constructor(
    public title: string,
    public relativePath: string,
    public component: any,
    public info: any = {},
    public parentRoute?: Route,
    public childRoutes?: Route[],
  ) {
    // Set self as parent to child routes
    if (this.childRoutes) {
      this.childRoutes.forEach(route => {
        route.parentRoute = this;
      });
    }
  }

  /**
   * Returns full route path composed from parent route full-path and route's relative path
   */
  public get fullPath(): string[] {
    return [...(this.parentRoute ? this.parentRoute.fullPath : []), this.relativePath];
  }
}
